###
# @name get
GET http://localhost:1337/v1/ HTTP/1.1

###
# @name fetchArticle
GET http://localhost:1337/v1/articles/1 HTTP/1.1

###
# @name fetchAllArticles
GET http://localhost:1337/v1/articles/ HTTP/1.1
