###
# @name get
GET http://localhost:1337/v1/ HTTP/1.1

###
# @name fetchUser
GET http://localhost:1337/v1/users/1 HTTP/1.1

###
# @name fetchAllUsers
GET http://localhost:1337/v1/users/ HTTP/1.1

###
# @name createUser
POST http://localhost:1337/v1/users/create HTTP/1.1
content-type: application/json

{
    "Name": "james",
    "Age": 36
}


###
# @name updateUser
PATCH http://localhost:1337/v1/users/9 HTTP/1.1
content-type: application/json

{
    "Name": "john",
    "Age": 40
}

###
# @name removeUser
DELETE http://localhost:1337/v1/users/1 HTTP/1.1